### PR TITLE
Add support for MRI 1.8, turn into gem

### PR DESCRIPTION
**Pull request by camertron**
Hey Martin,

I've been doing a bit of work recently on converting eprun into a gem and adding support for Ruby 1.8 (which is required by twitter-cldr-rb). Ultimately I'd like to make eprun a dependency and deprecate the existing normalization implementation we have today.

Some notes regarding this pull request:
1. Instead of using characters and strings as the keys and values for the normalization tables, I used Unicode codepoints. This is mostly to avoid string indexing and other issues in MRI 1.8. Similarly, all normalization regexes now use escaped octal character representations instead of Unicode escapes (eg \u11AB).
2. The test suite has been rewritten in RSpec (from Test::Unit).
3. The normalization table generator script has been turned into a rake task. Run `bundle exec rake generate_tables` to regenerate.
4. The benchmark suite is also a rake task. Run `bundle exec rake benchmark` to execute.
5. Eprun is now capable of running on the TravisCI build platform (see `.travis.yml`). You'll need to enable the git hook for automatic test runs in Eprun's admin config on GitHub and sign up for a free TravisCI account.
6. Because of the addition of MRI compatibility, Eprun's benchmarks have taken a bit of a hit. I noticed an average slow-down of about 400ms. To me, that's an acceptable level of degradation, but I'd like to hear what you think.
7. The project now works on all major versions of MRI, including 1.8, 1.9, and 2.0. I had to remove a few references to the `Encoding` class, particularly the functionality that would convert to UTF-8 from UTF-16 before performing normalization. This means that Eprun _must_ be used only with UTF-8 inputs. I don't know if there's anything we can do about that unless we'd like to guess at the encoding and use `Iconv` to convert.

Let me know what you think! As far as I know, Eprun is still the fastest Ruby normalization implementation out there. Thanks for your consideration!

-Cameron

### CODE REVIEW

**Comment by duerst** [comment]
Hello Cameron,

Many thanks for your interest and contribution! Here are my general comments (i.e. before looking at the code; will do that tomorrow):

re. 1.: It's great to make it work also on 1.8. I'm thinking about integrating your stuff, but with a switch between 1.8 and 1.9, so that we can keep the 1.9 code. (I'd not want to keep escaped octal in 10 years when 1.8 is no longer relevant.)
re. 2.: One of my plans is to get this into Ruby, so I'd want to keep Test::Unit. But there should be no problem in having double testing.
re. 3./4.: I wanted to create some rake tasks, too (one for the table generation and maybe one for updating the data files from the Unicode site), so I'm glad to get this. 4 also makes sense.
re. 5.: Didn't think that far, but makes sense. Thanks!
re. 6.: See re. 1.; if that works out, it won't be a problem at all.
re. 7.: I was never really sure about the UTF-16->UTF-8 thing myself. I think all other normalization libraries assume UTF-8, and I definitely want to push Ruby towards UTF-8 (where a push is still needed). I actually have a commit where I restrict the allowed encodings, because normalizing something like iso-8859-1 doesn't make much sense in the first place. This is also related to your point 1.

I definitely want to integrate your stuff, but I won't do it all in one go. Should I integrate it "by hand", meaning that it would be me committing (of course with a note mentioning you as the originator), or do you want to chop things up into finer-grained pull requests (or is there an even better way to do this, e.g. me pulling your stuff into a branch and then working from there,...)?

**Comment by camertron** [comment]
Hey Martin,

Great, thanks for your reply!
1.  Yes, that makes perfect sense.  I can think of two ways to do this: a) maintain two versions of the gem, one for 1.8 and one for >= 1.9, or b) add a conditional switch in `tables.rb` and generate both sets of normalization tables and regexes.  This means the `generate_tables` rake task would have to be run from a >= 1.9 implementation to successfully generate both sets of tables.  Let me know what you think :)
2.  Ah right, that makes sense.  I don't think there are any benefits to maintaining two different versions of the test suite, so I'm happy to revert the RSpec changes.
3.  Great!
4.  Great!
5.  We're adding travis configs to just about all of our open-source offerings these days.  Great tool to add to your open-source toolbox.
6.  Right, should be able to maintain two versions and optimize for performance.
7.  Absolutely, UTF-8 seems like the way forward.

Once we decide how to maintain two versions of the codebase (i.e. 1.8 vs >= 1.9), I'll go ahead and break up my changes into separate pull requests so we aren't dealing with so much all at once.  I'll submit the core changes first (octal escapes, etc), followed by the rake tasks, followed by the necessary changes to turn Eprun into a gem.  How does that sound?

**Comment by duerst** [comment]
Hello Cameron,

It was great to talk to you yesterday.

Just some notes trying to summarize our conversation, and some followup.

We'll go with a conditional switch in lib/eprun.rb, with 2 separate files for the tables and for the core code. I'd propose that the filenames (or the directory name) for >= 1.9 don't have any version suffix, but the ones for 1.8 have a 1.8-specific suffix. This means once 1.8 is gone, we can just yank these files. The main differences will be 1)  \u or actual characters vs. octal escapes; actual characters vs. character numbers in some of the tables, and direct use of hash as argument to gsub vs. block doing hash lookup explicitly. (During the call, I assumed that somebody had backported the use of a hash as a second argument back to 1.8, but I was wrong. It took me quite a while to figure that out digging through Ruby commit history; I should just have had a much closer look at your code.)

With respect to bundler, it should be acceptable as a dependency e.g. when generating the tables, but not for production. Similar for other dependencies that may be usual for Rails, but not for standalone ruby.

For namespacing, let's change the name of the outer module to Eprun, but avoid additional nesting (class Normalizer, module NormalizationTables, class Benchmarks,...) unless needed.

In lib/eprun.rb, (try to) remove encoding-related settings (Encoding.default_xxx, $KCODE), so that the code can be used in programs that use mixed encodings. My guess is that this should work if these settings are moved to the benchmark.rb file, because there we are reading in plain text data, and if we use a 'u' option for the regular expressions for 1.8. Our source (including tables) is all marked as being in UTF-8, so the rest should work automatically.

For the enable_core_extensions! method, it would be great if that could also still work the old way (require a single specific file).

As for patches, whatever size (big or small) works best is okay for me.

Again, lots of thanks for all your great help.    Regards,   Martin.

**Comment by camertron** [comment]
Hey @duerst, any idea when you'll have a chance to look at these changes?

**Comment by camertron** [comment]
Just checking in again, @duerst. What more needs to be done before these changes can be merged?

**Comment by duerst** [comment]
Hello Cameron,

Many thanks for closing this. Just a few pointers for why we can close this:
- Unicode Normalization has been included into Ruby itself, based on eprun, see https://bugs.ruby-lang.org/issues/10084. This is available from Ruby 2.0.0 onwards.
- For older versions, eprun, including Cameron's additions, is available as a gem at https://rubygems.org/gems/camertron-eprun.

**Pull request closed without merging**
